-- Basic
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')
-- Plugins
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.fluttertools')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
--require('plugins.nullls')
require('plugins.whichkey')
require('plugins.lualine')
require('plugins.gitsigns')
require('plugins.autopairs')
require('plugins.autotag')
require('plugins.bufferline')
require('plugins.comment')
require('plugins.termtoggle')
